name: Deploy to Railway

on:
  push:
    branches:
      - main

env:
  RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
  RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
  ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
  REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          git pull origin main
          npm install
          npm run migrate up

      - name: Deploy to Railway
        run: |
          railway login --token ${{ secrets.RAILWAY_TOKEN }}
          railway link ${{ secrets.RAILWAY_PROJECT_ID }}
          railway up --detach
