name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Railway CLI
        run: npm install -g @railway/cli@latest

      - name: Authenticate with Railway
        run: |
          railway login --ci ${{ secrets.RAILWAY_TOKEN }}
          railway whoami
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Link Project
        run: railway link ${{ secrets.RAILWAY_PROJECT_ID }}

      - name: Run Migrations
        run: railway run -- npm run migrate up
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Deploy
        run: railway up --detach
